### ISSUE TITLE
from app import app?

### ISSUE THREAD

**Issue by electroniceagle** [RentMethod/celerytest#1]
Think I'm missing something really basic, but what is 'app' in 'from app import app' supposed to be in the lettuce terrain example?

```
  File "/Users/bschott/Source/site-tss/site_common/terrain.py", line 31, in <module>
    from app import app
ImportError: No module named app
```

**Comment by willembult** [comment]
Ah, sorry. That's just an example and would work if your Celery app would be defined as "app" in the "app" module. Your real use case will likely be different. The import you need depends on where your actual Celery app lives. See http://celery.readthedocs.org/en/latest/getting-started/first-steps-with-celery.html#application.

If you're using djcelery with Django this would be

```
from djcelery.app import app
```

**Comment by willembult** [comment]
https://github.com/RentMethod/celerytest/commit/e85a894ee83e4da63b2bc681c42856e56ac803db
