### ISSUE TITLE
Broken on latest celery

### ISSUE THREAD

**Issue by kmmbvnr** [RentMethod/celerytest#3]
File "celerytest/celerytest/worker.py", line 39, in run
    worker.run()
AttributeError: 'Worker' object has no attribute 'run'

**Comment by willembult** [comment]
Thanks! Yes, this needs fixing. For new Celery, it looks like this should be:

``` python
worker.start()
```

So I think this would be safe:

``` python
if hasattr(worker, 'start'):
    worker.start()
elif hasattr(worker, 'run'):
    worker.run()
else:
    raise Exception("Don't know how to start this Celery Worker. Incompatible version?")
```

**Comment by willembult** [comment]
Fixed in https://github.com/RentMethod/celerytest/commit/0afe4ec204a6e70c25368725701caff44fe67a37

**Comment by ccorcos** [comment]
I'm getting this error -- has this new version been released yet?
